# -*- coding: utf-8 -*-
"""Expense Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R538im3Y6fFCSmWI7mAR015PIlQN47Es
"""

import argparse, sqlite3, csv, json
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

DB_FILE = "expenses.db"

def init_db():
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()
    cur.execute("""CREATE TABLE IF NOT EXISTS entries (
        id INTEGER PRIMARY KEY,
        date TEXT,
        category TEXT,
        amount REAL,
        type TEXT
    )""")
    conn.commit()
    conn.close()

def add_entry(date, category, amount, etype):
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()
    cur.execute("INSERT INTO entries (date, category, amount, type) VALUES (?,?,?,?)",
                (date, category, amount, etype))
    conn.commit()
    conn.close()

def monthly_summary(month, year):
    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql_query("SELECT * FROM entries", conn)
    conn.close()
    df["date"] = pd.to_datetime(df["date"])
    df_month = df[(df["date"].dt.month == month) & (df["date"].dt.year == year)]
    income = df_month[df_month["type"]=="income"]["amount"].sum()
    expense = df_month[df_month["type"]=="expense"]["amount"].sum()
    balance = income - expense
    print(f"Summary {month}/{year}: Income={income}, Expense={expense}, Balance={balance}")
    return df_month

def export_data(fmt, outfile):
    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql_query("SELECT * FROM entries", conn)
    conn.close()
    if fmt=="csv":
        df.to_csv(outfile, index=False)
    elif fmt=="excel":
        df.to_excel(outfile, index=False)

def plot_chart(df, outfile):
    df.groupby("category")["amount"].sum().plot(kind="bar")
    plt.title("Expenses by Category")
    plt.savefig(outfile)

def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command")

    add_parser = subparsers.add_parser("add")
    add_parser.add_argument("--date", required=True)
    add_parser.add_argument("--category", required=True)
    add_parser.add_argument("--amount", type=float, required=True)
    add_parser.add_argument("--type", choices=["income","expense"], required=True)

    summary_parser = subparsers.add_parser("summary")
    summary_parser.add_argument("--month", type=int, required=True)
    summary_parser.add_argument("--year", type=int, required=True)

    export_parser = subparsers.add_parser("export")
    export_parser.add_argument("--format", choices=["csv","excel"], required=True)
    export_parser.add_argument("--output", required=True)

    chart_parser = subparsers.add_parser("chart")
    chart_parser.add_argument("--month", type=int, required=True)
    chart_parser.add_argument("--year", type=int, required=True)
    chart_parser.add_argument("--output", required=True)

    args = parser.parse_args()
    init_db()

    if args.command=="add":
        add_entry(args.date, args.category, args.amount, args.type)
    elif args.command=="summary":
        monthly_summary(args.month, args.year)
    elif args.command=="export":
        export_data(args.format, args.output)
    elif args.command=="chart":
        df = monthly_summary(args.month, args.year)
        plot_chart(df, args.output)

# Only run CLI if executed directly
if __name__ == "__main__":
    main()