# -*- coding: utf-8 -*-
"""FolderBackupSyncTool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uEbdgDvpjFE5PYjyYPvDJTZ5A3YVHeD
"""

import argparse
import os
import shutil
import logging
import time
import zipfile
from datetime import datetime

def setup_logging():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[logging.StreamHandler()]
    )

def parse_args():
    parser = argparse.ArgumentParser(description="Folder Backup/Sync Tool: Backs up a source folder to a destination. If no source or destination is provided, it will use default paths.")
    parser.add_argument("--source", default="/content/source_folder", help="Source folder to backup (default: /content/source_folder)")
    parser.add_argument("--destination", default="/content/destination_folder", help="Destination folder (default: /content/destination_folder)")
    parser.add_argument("--dry-run", action="store_true", help="Simulate actions without copying")
    parser.add_argument("--compress", action="store_true", help="Compress backup into a zip file")
    parser.add_argument("--rotate", type=int, default=0, help="Number of old backups to keep")
    return parser.parse_args()

def incremental_backup(src, dest, dry_run=False, compress=False, rotate=0):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_dir = os.path.join(dest, f"backup_{timestamp}")

    if compress:
        backup_file = f"{backup_dir}.zip"
        logging.info(f"Creating compressed backup: {backup_file}")
        if not dry_run:
            with zipfile.ZipFile(backup_file, "w", zipfile.ZIP_DEFLATED) as zipf:
                for root, _, files in os.walk(src):
                    for file in files:
                        filepath = os.path.join(root, file)
                        arcname = os.path.relpath(filepath, src)
                        zipf.write(filepath, arcname)
    else:
        logging.info(f"Creating backup folder: {backup_dir}")
        if not dry_run:
            shutil.copytree(src, backup_dir)

    if rotate > 0:
        rotate_backups(dest, rotate)

def rotate_backups(dest, keep):
    backups = sorted(
        [f for f in os.listdir(dest) if f.startswith("backup_")],
        key=lambda x: os.path.getmtime(os.path.join(dest, x))
    )
    while len(backups) > keep:
        old = backups.pop(0)
        old_path = os.path.join(dest, old)
        logging.info(f"Removing old backup: {old_path}")
        if os.path.isdir(old_path):
            shutil.rmtree(old_path)
        elif os.path.isfile(old_path):
            os.remove(old_path)

def main():
    setup_logging()

    # Temporarily modify sys.argv to prevent argparse from seeing kernel arguments
    import sys
    original_argv = sys.argv
    sys.argv = [sys.argv[0]] # Keep only the script name

    try:
        args = parse_args()
    finally:
        sys.argv = original_argv # Always restore sys.argv

    logging.info(f"Source: {args.source}")
    logging.info(f"Destination: {args.destination}")
    logging.info(f"Dry run: {args.dry_run}")
    logging.info(f"Compress: {args.compress}")
    logging.info(f"Rotate: {args.rotate}")

    # Create source and destination directories if they don't exist
    if not os.path.exists(args.source):
        os.makedirs(args.source, exist_ok=True)
        logging.info(f"Created source directory: {args.source}")
    if not os.path.exists(args.destination):
        os.makedirs(args.destination, exist_ok=True)
        logging.info(f"Created destination directory: {args.destination}")

    incremental_backup(args.source, args.destination, args.dry_run, args.compress, args.rotate)

if __name__ == "__main__":
    main()

